apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationmanagement
  labels:
    app: notificationmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationmanagement
  template:
    metadata:
      labels:
        app: notificationmanagement
    spec:
      containers:
        - name: notificationmanagement
          image: skcc02acr.azurecr.io/notificationmanagement:latest
          ports:
            - containerPort: 8080
